 spring:
      datasource:
                url: jdbc:mysql://localhost:3306/test
                username: root
                password: root
                driver-class-name: com.mysql.jdbc.Driver
      jpa:
         database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      hibernate.ddl-auto: update
 server.port: 8087 
      
#logging.level.root: "WARN"

